"""Qt compatibility layer.

Prefers PySide6 and falls back to PyQt6 when needed.
Exports a unified symbol set used by the application.
"""

try:
    # PySide6
    from PySide6.QtCore import (
        QEasingCurve,
        QDateTime,
        QEvent,
        QFileSystemWatcher,
        QObject,
        QPoint,
        QRect,
        QPropertyAnimation,
        QSize,
        QStringListModel,
        QThread,
        QTime,
        QTimer,
        QUrl,
        Qt,
        Signal,
    )
    from PySide6.QtGui import QAction, QColor, QIcon, QPainter, QPainterPath, QPen, QPixmap
    from PySide6.QtNetwork import QNetworkAccessManager, QNetworkReply, QNetworkRequest
    from PySide6.QtWidgets import (
        QApplication,
        QButtonGroup,
        QCheckBox,
        QComboBox,
        QCompleter,
        QDateTimeEdit,
        QFileDialog,
        QFrame,
        QGraphicsOpacityEffect,
        QGraphicsDropShadowEffect,
        QGridLayout,
        QHBoxLayout,
        QLabel,
        QLineEdit,
        QListView,
        QListWidget,
        QMainWindow,
        QMenu,
        QMessageBox,
        QPushButton,
        QProgressBar,
        QRadioButton,
        QScrollArea,
        QSlider,
        QSpinBox,
        QStackedWidget,
        QStyle,
        QSystemTrayIcon,
        QTextEdit,
        QTimeEdit,
        QVBoxLayout,
        QWidget,
    )
except ImportError:
    # PyQt6 fallback
    from PyQt6.QtCore import (
        QEasingCurve,
        QDateTime,
        QEvent,
        QFileSystemWatcher,
        QObject,
        QPoint,
        QRect,
        QPropertyAnimation,
        QSize,
        QStringListModel,
        QThread,
        QTime,
        QTimer,
        QUrl,
        Qt,
        pyqtSignal as Signal,
    )
    from PyQt6.QtGui import QAction, QColor, QIcon, QPainter, QPainterPath, QPen, QPixmap
    from PyQt6.QtNetwork import QNetworkAccessManager, QNetworkReply, QNetworkRequest
    from PyQt6.QtWidgets import (
        QApplication,
        QButtonGroup,
        QCheckBox,
        QComboBox,
        QCompleter,
        QDateTimeEdit,
        QFileDialog,
        QFrame,
        QGraphicsOpacityEffect,
        QGraphicsDropShadowEffect,
        QGridLayout,
        QHBoxLayout,
        QLabel,
        QLineEdit,
        QListView,
        QListWidget,
        QMainWindow,
        QMenu,
        QMessageBox,
        QPushButton,
        QProgressBar,
        QRadioButton,
        QScrollArea,
        QSlider,
        QSpinBox,
        QStackedWidget,
        QStyle,
        QSystemTrayIcon,
        QTextEdit,
        QTimeEdit,
        QVBoxLayout,
        QWidget,
    )

__all__ = [
    "QThread",
    "Qt",
    "Signal",
    "QUrl",
    "QTimer",
    "QPropertyAnimation",
    "QEasingCurve",
    "QDateTime",
    "QStringListModel",
    "QTime",
    "QSize",
    "QPoint",
    "QRect",
    "QFileSystemWatcher",
    "QObject",
    "QEvent",
    "QNetworkAccessManager",
    "QNetworkRequest",
    "QNetworkReply",
    "QIcon",
    "QAction",
    "QPixmap",
    "QPainter",
    "QColor",
    "QPen",
    "QPainterPath",
    "QApplication",
    "QButtonGroup",
    "QCheckBox",
    "QComboBox",
    "QCompleter",
    "QFileDialog",
    "QFrame",
    "QGraphicsDropShadowEffect",
    "QGridLayout",
    "QHBoxLayout",
    "QLabel",
    "QLineEdit",
    "QListView",
    "QListWidget",
    "QMainWindow",
    "QMessageBox",
    "QPushButton",
    "QProgressBar",
    "QRadioButton",
    "QScrollArea",
    "QSlider",
    "QSpinBox",
    "QStackedWidget",
    "QTextEdit",
    "QTimeEdit",
    "QVBoxLayout",
    "QWidget",
    "QGraphicsOpacityEffect",
    "QSystemTrayIcon",
    "QMenu",
    "QStyle",
    "QDateTimeEdit",
]
